package Interfaces;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author lipen
 */
public class jifConsultaA extends javax.swing.JInternalFrame {

    /**
     * Creates new form jifConsultaA
     */
    public jifConsultaA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jlBio2 = new javax.swing.JLabel();
        jlMat1 = new javax.swing.JLabel();
        jlMat2 = new javax.swing.JLabel();
        jlMat3 = new javax.swing.JLabel();
        jlPort1 = new javax.swing.JLabel();
        jlPort2 = new javax.swing.JLabel();
        jlBio3 = new javax.swing.JLabel();
        jlHist1 = new javax.swing.JLabel();
        jlGeo1 = new javax.swing.JLabel();
        jlFis1 = new javax.swing.JLabel();
        jlQuim1 = new javax.swing.JLabel();
        jlBio1 = new javax.swing.JLabel();
        jlHist2 = new javax.swing.JLabel();
        jlGeo2 = new javax.swing.JLabel();
        jlFis2 = new javax.swing.JLabel();
        jlQuim2 = new javax.swing.JLabel();
        jlPort3 = new javax.swing.JLabel();
        jlHist3 = new javax.swing.JLabel();
        jlGeo3 = new javax.swing.JLabel();
        jlFis3 = new javax.swing.JLabel();
        jlQuim3 = new javax.swing.JLabel();
        jbFechar = new javax.swing.JButton();
        jbVoltar= new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        ActionVoltar actionVoltar = new ActionVoltar();

        ActionFechar actionFechar = new ActionFechar();

        getContentPane().setLayout(null);


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome Aluno");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(24, 18, 186, 16);

        jLabel2.setText("Turma:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(340, 20, 50, 16);

        jLabel3.setText("Nome da turma");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(380, 20, 100, 16);

        jLabel4.setText("Biologia");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 190, 80, 16);

        jLabel5.setText("Matemática");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 70, 80, 16);

        jLabel6.setText("Português");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 90, 80, 16);

        jLabel7.setText("História");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 110, 80, 16);

        jLabel8.setText("Geografia");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 130, 80, 16);

        jLabel9.setText("Física");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 150, 80, 16);

        jLabel10.setText("Química");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 170, 80, 16);

        jLabel11.setText("Prova 3");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(400, 50, 39, 16);

        jLabel12.setText("Prova 1");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(280, 50, 50, 16);

        jLabel13.setText("Prova 2");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(340, 50, 39, 16);

        jlBio2.setText("0.0");
        getContentPane().add(jlBio2);
        jlBio2.setBounds(340, 190, 43, 16);

        jlMat1.setText("0.0");
        getContentPane().add(jlMat1);
        jlMat1.setBounds(280, 70, 15, 16);

        jlMat2.setText("0.0");
        getContentPane().add(jlMat2);
        jlMat2.setBounds(340, 70, 43, 16);

        jlMat3.setText("0.0");
        getContentPane().add(jlMat3);
        jlMat3.setBounds(400, 70, 43, 16);

        jlPort1.setText("0.0");
        getContentPane().add(jlPort1);
        jlPort1.setBounds(280, 90, 43, 16);

        jlPort2.setText("0.0");
        getContentPane().add(jlPort2);
        jlPort2.setBounds(340, 90, 43, 16);

        jlBio3.setText("0.0");
        getContentPane().add(jlBio3);
        jlBio3.setBounds(400, 190, 43, 16);

        jlHist1.setText("0.0");
        getContentPane().add(jlHist1);
        jlHist1.setBounds(280, 110, 43, 16);

        jlGeo1.setText("0.0");
        getContentPane().add(jlGeo1);
        jlGeo1.setBounds(280, 130, 43, 16);

        jlFis1.setText("0.0");
        getContentPane().add(jlFis1);
        jlFis1.setBounds(280, 150, 43, 16);

        jlQuim1.setText("0.0");
        getContentPane().add(jlQuim1);
        jlQuim1.setBounds(280, 170, 43, 16);

        jlBio1.setText("0.0");
        getContentPane().add(jlBio1);
        jlBio1.setBounds(280, 190, 43, 16);

        jlHist2.setText("0.0");
        getContentPane().add(jlHist2);
        jlHist2.setBounds(340, 110, 43, 16);

        jlGeo2.setText("0.0");
        getContentPane().add(jlGeo2);
        jlGeo2.setBounds(340, 130, 43, 16);

        jlFis2.setText("0.0");
        getContentPane().add(jlFis2);
        jlFis2.setBounds(340, 150, 43, 16);

        jlQuim2.setText("0.0");
        getContentPane().add(jlQuim2);
        jlQuim2.setBounds(340, 170, 43, 16);

        jlPort3.setText("0.0");
        getContentPane().add(jlPort3);
        jlPort3.setBounds(400, 90, 43, 16);

        jlHist3.setText("0.0");
        getContentPane().add(jlHist3);
        jlHist3.setBounds(400, 110, 43, 16);

        jlGeo3.setText("0.0");
        getContentPane().add(jlGeo3);
        jlGeo3.setBounds(400, 130, 43, 16);

        jlFis3.setText("0.0");
        getContentPane().add(jlFis3);
        jlFis3.setBounds(400, 150, 43, 16);

        jlQuim3.setText("0.0");
        getContentPane().add(jlQuim3);
        jlQuim3.setBounds(400, 170, 43, 16);

        jbFechar.setText("Fechar");
        jbFechar.addActionListener(actionFechar);
        getContentPane().add(jbFechar);
        jbFechar.setBounds(310, 280, 75, 23);

        jbVoltar.setText("Voltar");
        getContentPane().add(jbVoltar);
        jbVoltar.addActionListener(actionVoltar);
        jbVoltar.setBounds(100, 280, 72, 23);

        jLabel14.setText("Presença");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(450, 50, 60, 16);

        jLabel16.setText("100%");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(470, 70, 28, 16);

        jLabel19.setText("100%");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(470, 190, 43, 16);

        jLabel20.setText("100%");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(470, 90, 43, 16);

        jLabel21.setText("100%");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(470, 110, 43, 16);

        jLabel22.setText("100%");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(470, 130, 43, 16);

        jLabel23.setText("100%");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(470, 150, 43, 16);

        jLabel24.setText("100%");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(470, 170, 43, 16);

        setBounds(0, 0, 537, 414);
    }// </editor-fold>//GEN-END:initComponents

    private class ActionVoltar implements ActionListener {
        public void actionPerformed(ActionEvent event){
            dispose();;
        
    }
}

    private class ActionFechar implements ActionListener {
        public void actionPerformed(ActionEvent event){
        System.exit(0);}
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbFechar;
    private javax.swing.JButton jbVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jlBio1;
    private javax.swing.JLabel jlBio2;
    private javax.swing.JLabel jlBio3;
    private javax.swing.JLabel jlFis1;
    private javax.swing.JLabel jlFis2;
    private javax.swing.JLabel jlFis3;
    private javax.swing.JLabel jlGeo1;
    private javax.swing.JLabel jlGeo2;
    private javax.swing.JLabel jlGeo3;
    private javax.swing.JLabel jlHist1;
    private javax.swing.JLabel jlHist2;
    private javax.swing.JLabel jlHist3;
    private javax.swing.JLabel jlMat1;
    private javax.swing.JLabel jlMat2;
    private javax.swing.JLabel jlMat3;
    private javax.swing.JLabel jlPort1;
    private javax.swing.JLabel jlPort2;
    private javax.swing.JLabel jlPort3;
    private javax.swing.JLabel jlQuim1;
    private javax.swing.JLabel jlQuim2;
    private javax.swing.JLabel jlQuim3;
    // End of variables declaration//GEN-END:variables
}
