/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interfaces;

import java.awt.event.ActionEvent;
import java.util.EventListener;
import java.awt.event.ActionListener;
import javax.swing.*;
import java.awt.*;




/**
 *
 * @author lipen
 * 
 * 
 */





public class jifCadastroA extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cadastro
     */
    public jifCadastroA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtCpf = new javax.swing.JTextField();
        jtNome = new javax.swing.JTextField();
        jtNatu = new javax.swing.JTextField();
        jtIdade = new javax.swing.JTextField();
        jbVoltar = new javax.swing.JButton();
        jbNovo = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtTurma = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtSenhaRep = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtSenha = new javax.swing.JTextField();

       
        ActionSalvar actionSalvar = new ActionSalvar();
        ActionNovo actionNovo = new ActionNovo();

        ActionLimpar actionLimpar = new ActionLimpar();
        ActionVoltar actionVoltar = new ActionVoltar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Aluno");
        getContentPane().setLayout(null);

        jLabel1.setText("CPF");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 160, 50, 20);

        jLabel2.setText("Idade");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 80, 70, 20);

        jLabel3.setText("Naturalidade");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 120, 100, 20);

        jLabel4.setText("Nome");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 40, 70, 20);

        getContentPane().add(jtCpf);
        jtCpf.setBounds(50, 180, 240, 25);
        getContentPane().add(jtNome);
        jtNome.setBounds(50, 60, 240, 25);
        getContentPane().add(jtNatu);
        jtNatu.setBounds(50, 140, 240, 25);
        getContentPane().add(jtIdade);
        jtIdade.setBounds(50, 100, 240, 25);

        jbVoltar.setText("Voltar");
        getContentPane().add(jbVoltar);
        jbVoltar.addActionListener(actionVoltar);
        jbVoltar.setBounds(390, 300, 72, 23);

        jbNovo.setText("Novo");
        jbNovo.addActionListener(actionNovo);
        getContentPane().add(jbNovo);
        jbNovo.setBounds(70, 260, 72, 23);

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(actionLimpar);
        getContentPane().add(jbLimpar);
        jbLimpar.setBounds(70, 300, 72, 23);

        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(actionSalvar);
        getContentPane().add(jbSalvar);
        jbSalvar.setBounds(390, 260, 72, 23);

        jLabel5.setText("Turma");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 200, 90, 20);

        
        getContentPane().add(jtTurma);
        jtTurma.setBounds(50, 220, 240, 25);

        jLabel6.setText("Repetir Senha");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(330, 100, 130, 20);
        getContentPane().add(jtSenhaRep);
        jtSenhaRep.setBounds(330, 120, 180, 22);

        jLabel7.setText("Senha");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(330, 50, 50, 20);
        getContentPane().add(jtSenha);
        jtSenha.setBounds(330, 70, 180, 22);

        setBounds(0, 0, 581, 446);
    }// </editor-fold>//GEN-END:initComponents

 
    private class ActionLimpar implements ActionListener{
        public void actionPerformed(ActionEvent event){
            jtNome.setText("");
            jtCpf.setText("");
            jtIdade.setText("");
            jtNatu.setText("");
            jtTurma.setText("");
            jtSenha.setText("");
            jtSenhaRep.setText("");

        }
    }

    private class ActionVoltar implements ActionListener{
        public void actionPerformed(ActionEvent event){
            dispose();
        }
    }

    private class ActionSalvar implements ActionListener{
        public void actionPerformed(ActionEvent event){
            JOptionPane.showMessageDialog(null, "Dados salvos!");
        }
    }

    private class ActionNovo implements ActionListener{
        public void actionPerformed(ActionEvent event){
            jtNome.setText("");
            jtCpf.setText("");
            jtIdade.setText("");
            jtNatu.setText("");
            jtTurma.setText("");
            jtSenha.setText("");
            jtSenhaRep.setText("");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JButton jbVoltar;
    private javax.swing.JTextField jtCpf;
    private javax.swing.JTextField jtIdade;
    private javax.swing.JTextField jtNatu;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtSenha;
    private javax.swing.JTextField jtSenhaRep;
    private javax.swing.JTextField jtTurma;
    // End of variables declaration//GEN-END:variables
}
