/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.*;

/**
 *
 * @author lipen
 */
public class jifCadastroP extends javax.swing.JInternalFrame {

    /**
     * Creates new form jifCadastroP
     */
    public jifCadastroP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NovoAction novoAction = new NovoAction();
        LimparAction limparAction = new LimparAction();
        VoltarAction voltarAction = new VoltarAction();

        jLabel1 = new javax.swing.JLabel();
        jtfNatu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfCpf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfIdade = new javax.swing.JTextField();
        jbVoltar = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtfSenhaRep = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfSenha = new javax.swing.JTextField();
        jbNovo = new javax.swing.JButton();

        
        

        

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Professor");
        getContentPane().setLayout(null);

        jLabel1.setText("Naturalidade");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 140, 110, 16);
        getContentPane().add(jtfNatu);
        jtfNatu.setBounds(20, 160, 180, 22);

        jLabel2.setText("Nome");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 20, 90 , 16);
        getContentPane().add(jtfNome);
        jtfNome.setBounds(20, 40, 180, 22);

        jLabel3.setText("CPF");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 60, 80, 16);
        getContentPane().add(jtfCpf);
        jtfCpf.setBounds(20, 80, 180, 22);

        jLabel4.setText("Idade");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 100, 80, 16);
        getContentPane().add(jtfIdade);
        jtfIdade.setBounds(20, 120, 180, 22);

        jbVoltar.setText("Voltar");
        jbVoltar.addActionListener(voltarAction);
        getContentPane().add(jbVoltar);
        jbVoltar.setBounds(390, 330, 75, 23);

        jbSalvar.setText("Salvar");
        getContentPane().add(jbSalvar);
        jbSalvar.setBounds(390, 290, 75, 23);

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(limparAction);
        getContentPane().add(jbLimpar);
        jbLimpar.setBounds(70, 330, 75, 23);

        jLabel5.setText("Repetir Senha");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(290, 60, 120, 16);
        getContentPane().add(jtfSenhaRep);
        jtfSenhaRep.setBounds(290, 80, 130, 22);

        jLabel6.setText("Senha");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(290, 20, 70, 16);
        getContentPane().add(jtfSenha);
        jtfSenha.setBounds(290, 40, 130, 22);

        jbNovo.setText("Novo");
        jbNovo.addActionListener(novoAction);
        getContentPane().add(jbNovo);
        jbNovo.setBounds(70, 290, 72, 23);

        setBounds(0, 0, 548, 432);
    }// </editor-fold>//GEN-END:initComponents


    private class VoltarAction implements ActionListener{
        public void actionPerformed(ActionEvent event)
        {
            dispose();
        }
    }

    private class LimparAction implements ActionListener{

        public void actionPerformed(ActionEvent event){
            jtfNome.setText("");
            jtfCpf.setText("");
            jtfIdade.setText("");
            jtfNatu.setText("");
            jtfSenha.setText("");
            jtfSenhaRep.setText("");

        }


    }

    private class NovoAction implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent event ){
            jtfNome.setText("");
            jtfCpf.setText("");
            jtfIdade.setText("");
            jtfNatu.setText("");
            jtfSenha.setText("");
            jtfSenhaRep.setText("");

        }
    }

  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jifCadastroP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jifCadastroP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jifCadastroP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jifCadastroP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new jifCadastroP().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JButton jbVoltar;
    private javax.swing.JTextField jtfCpf;
    private javax.swing.JTextField jtfIdade;
    private javax.swing.JTextField jtfNatu;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfSenha;
    private javax.swing.JTextField jtfSenhaRep;
    // End of variables declaration//GEN-END:variables
}
