/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interfaces;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.*;
import javax.swing.*;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lipen
 */
public class jifIncluirNota extends javax.swing.JInternalFrame{

    /**
     * Creates new form jifTurma
     */
    public jifIncluirNota() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtIncluirNota = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jtMatricula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jbIncluir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtMat = new javax.swing.JTextField();
        jtFis = new javax.swing.JTextField();
        jtQuim = new javax.swing.JTextField();
        jtBio = new javax.swing.JTextField();
        jtGeo = new javax.swing.JTextField();
        jtPresenca = new javax.swing.JTextField();
        jtPor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtHist1 = new javax.swing.JTextField();
        jbExcluir = new javax.swing.JButton();
        jbVoltar = new javax.swing.JButton();

        ActionIncluir actionIncluir = new ActionIncluir();
        ActionExcluir actionExcluir = new ActionExcluir();
        ActionVoltar actionVoltar = new ActionVoltar();



        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Turma");
        getContentPane().setLayout(null);

        jtIncluirNota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricula", "Mat", "Por", "Fis", "Quim", "Bio", "Geo", "Hist", "Pres"
            }
        ));
        jScrollPane1.setViewportView(jtIncluirNota);
        if (jtIncluirNota.getColumnModel().getColumnCount() > 0) {
            jtIncluirNota.getColumnModel().getColumn(0).setHeaderValue("Matricula");
            jtIncluirNota.getColumnModel().getColumn(1).setHeaderValue("Mat");
            jtIncluirNota.getColumnModel().getColumn(2).setHeaderValue("Por");
            jtIncluirNota.getColumnModel().getColumn(3).setHeaderValue("Fis");
            jtIncluirNota.getColumnModel().getColumn(4).setHeaderValue("Quim");
            jtIncluirNota.getColumnModel().getColumn(5).setHeaderValue("Bio");
            jtIncluirNota.getColumnModel().getColumn(6).setHeaderValue("Geo");
            jtIncluirNota.getColumnModel().getColumn(7).setHeaderValue("Hist");
            jtIncluirNota.getColumnModel().getColumn(8).setHeaderValue("Pres");
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 170, 530, 240);

        jLabel2.setText("Matricula");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 10, 60, 16);
        getContentPane().add(jtMatricula);
        jtMatricula.setBounds(100, 10, 110, 22);

        jLabel3.setText("Pres");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(300, 90, 40, 16);

        jbIncluir.setText("Incluir");
        jbIncluir.addActionListener(actionIncluir);
        getContentPane().add(jbIncluir);
        jbIncluir.setBounds(450, 20, 72, 23);

        jLabel4.setText("Mat");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 50, 40, 16);

        jLabel5.setText("Por");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 70, 40, 16);

        jLabel6.setText("Fis");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 90, 40, 16);

        jLabel7.setText("Quim");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 110, 40, 16);

        jLabel8.setText("Bio");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 130, 40, 16);

        jLabel9.setText("Geo");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(300, 50, 40, 25);

        getContentPane().add(jtMat);
        jtMat.setBounds(70, 50, 50, 25);
        getContentPane().add(jtFis);
        jtFis.setBounds(70, 90, 50, 25);
        getContentPane().add(jtQuim);
        jtQuim.setBounds(70, 110, 50, 25);
        getContentPane().add(jtBio);
        jtBio.setBounds(70, 130, 50, 25);
        getContentPane().add(jtGeo);
        jtGeo.setBounds(330, 50, 50, 25);
        getContentPane().add(jtPresenca);
        jtPresenca.setBounds(330, 90, 50, 25);
        getContentPane().add(jtPor);
        jtPor.setBounds(70, 70, 50, 25);

        jLabel10.setText("Nota");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(340, 30, 26, 16);

        jLabel11.setText("Nota");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(80, 30, 26, 16);

        jLabel12.setText("Hist");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(300, 70, 40, 16);


        getContentPane().add(jtHist1);
        jtHist1.setBounds(330, 70, 50, 25);

        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(actionExcluir);
        getContentPane().add(jbExcluir);
        jbExcluir.setBounds(450, 130, 72, 23);

        jbVoltar.setText("Voltar");
        jbVoltar.addActionListener(actionVoltar);
        getContentPane().add(jbVoltar);
        jbVoltar.setBounds(450, 150, 72, 23);

        setBounds(0, 0, 561, 460);
    }

   

    public class ActionIncluir implements ActionListener {
        public void actionPerformed(ActionEvent event) {
            DefaultTableModel model = (DefaultTableModel) jtIncluirNota.getModel();
            
            // Coletando dados das caixas de texto
            Object[] dados = {
                jtMatricula.getText(),
                jtMat.getText(),
                jtPor.getText(),
                jtFis.getText(),
                jtQuim.getText(),
                jtBio.getText(),
                jtGeo.getText(),
                jtHist1.getText(),
                jtPresenca.getText()
                
            };
            
            // Adicionando a linha à tabela
            model.addRow(dados);
        }
    }

    public class ActionExcluir implements ActionListener {
        public void actionPerformed(ActionEvent event) {
            int selectedRow = jtIncluirNota.getSelectedRow();
            
            // Verificando se há uma linha selecionada
            if (selectedRow != -1) {
                DefaultTableModel model = (DefaultTableModel) jtIncluirNota.getModel();

                model.removeRow(selectedRow);
            } else {
                JOptionPane.showMessageDialog(null, "Selecione uma linha para excluir.");
            }
        }
    }

    private class ActionVoltar implements ActionListener{
        public void actionPerformed(ActionEvent event){
            dispose();
        }
    }


    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbIncluir;
    private javax.swing.JButton jbVoltar;
    private javax.swing.JTextField jtBio;
    private javax.swing.JTextField jtFis;
    private javax.swing.JTextField jtGeo;
    private javax.swing.JTextField jtHist1;
    private javax.swing.JTable jtIncluirNota;
    private javax.swing.JTextField jtMat;
    private javax.swing.JTextField jtMatricula;
    private javax.swing.JTextField jtPor;
    private javax.swing.JTextField jtPresenca;
    private javax.swing.JTextField jtQuim;
    // End of variables declaration//GEN-END:variables
}
