
package Interfaces;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author lipen
 */
public class jifIncluirProvas extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultaAA
     */
    public jifIncluirProvas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jlProfessor = new javax.swing.JLabel();
        jProfessor = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTurma = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtMatricula = new javax.swing.JTextField();
        jtAluno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtP3 = new javax.swing.JTextField();
        jtP1 = new javax.swing.JTextField();
        jtP2 = new javax.swing.JTextField();
        jbBusca = new javax.swing.JButton();
        jbVoltar = new javax.swing.JButton();
        jbIncluir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jlMedia = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtProvas = new javax.swing.JTable();
        jlMateria = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jlAlunoMatriculaEncontrado = new javax.swing.JLabel();
        jlAlunoNomeEncontrado1 = new javax.swing.JLabel();

        ActionVoltar actionVoltar = new ActionVoltar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jToggleButton1.setText("jToggleButton1");

        getContentPane().setLayout(null);

        jlProfessor.setText("Professor:");
        getContentPane().add(jlProfessor);
        jlProfessor.setBounds(40, 20, 60, 20);

        jProfessor.setText("---");
        getContentPane().add(jProfessor);
        jProfessor.setBounds(100, 20, 200, 20);

        jLabel3.setText("Turma");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(460, 30, 50, 30);

        jTurma.setText("---");
        getContentPane().add(jTurma);
        jTurma.setBounds(520, 30, 80, 30);

        jLabel5.setText("Matricula:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 80, 60, 30);

        jLabel6.setText("Aluno:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 110, 60, 30);
        getContentPane().add(jtMatricula);
        jtMatricula.setBounds(120, 90, 180, 22);
        getContentPane().add(jtAluno);
        jtAluno.setBounds(120, 120, 180, 22);

        jLabel1.setText("Prova 3");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(550, 90, 50, 16);

        jLabel2.setText("Prova 1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(420, 90, 50, 16);

        jLabel4.setText("Prova 2");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(480, 90, 50, 16);
        getContentPane().add(jtP3);
        jtP3.setBounds(540, 110, 71, 22);
        getContentPane().add(jtP1);
        jtP1.setBounds(410, 110, 64, 22);
        getContentPane().add(jtP2);
        jtP2.setBounds(470, 110, 71, 22);

        jbBusca.setText("Buscar");
        getContentPane().add(jbBusca);
        jbBusca.setBounds(310, 120, 75, 23);

        ActionIncluir actionIncluir = new ActionIncluir();

        jbIncluir.setText("Incluir");
        getContentPane().add(jbIncluir);
        jbIncluir.addActionListener(actionIncluir);
        jbIncluir.setBounds(620, 110, 72, 23);

        jbVoltar.setText("Voltar");
        getContentPane().add(jbVoltar);
        jbVoltar.addActionListener(actionVoltar);
        jbVoltar.setBounds(620, 80, 72, 23);

        jLabel7.setText("Media:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(440, 160, 50, 30);

        jlMedia.setText("---");
        getContentPane().add(jlMedia);
        jlMedia.setBounds(500, 160, 60, 30);

        jtProvas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Aluno", "Prova 1", "Prova 2", "Prova 3", "Media"
            }
        ));
        jScrollPane2.setViewportView(jtProvas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 230, 740, 240);

        jlMateria.setText("*******");
        getContentPane().add(jlMateria);
        jlMateria.setBounds(120, 50, 90, 16);

        jLabel9.setText("Materia");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 50, 60, 16);

        jlAlunoMatriculaEncontrado.setText("----------------");
        getContentPane().add(jlAlunoMatriculaEncontrado);
        jlAlunoMatriculaEncontrado.setBounds(70, 190, 190, 16);

        jlAlunoNomeEncontrado1.setText("----------------");
        getContentPane().add(jlAlunoNomeEncontrado1);
        jlAlunoNomeEncontrado1.setBounds(70, 160, 190, 16);

        setBounds(0, 0, 754, 512);
    }// </editor-fold>//GEN-END:initComponents


     public class ActionIncluir implements ActionListener {
        public void actionPerformed(ActionEvent event) {
            // Verificar se todos os campos estão preenchidos
            if (jtAluno.getText().isEmpty() || jtP1.getText().isEmpty() || jtP2.getText().isEmpty() || jtP3.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos antes de incluir!");
                return;
            }
    
            try {
                // Coletar as notas das provas
                double p1 = Double.parseDouble(jtP1.getText());
                double p2 = Double.parseDouble(jtP2.getText());
                double p3 = Double.parseDouble(jtP3.getText());

                // Calcular a média
                double media = (p1 + p2 + p3) / 3;
                
                jlMedia.setText(String.valueOf(media));
                // Adicionar dados à tabela
                DefaultTableModel model = (DefaultTableModel) jtProvas.getModel();
                Object[] dados = {
                    jtAluno.getText(),p1,p2,p3,String.format("%.2f", media)
                };

                model.addRow(dados);
                

              
                // Limpar os campos de entrada
                jtAluno.setText("");
                jtP1.setText("");
                jtP2.setText("");
                jtP3.setText("");
             

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Insira apenas valores numéricos para as notas.");
            }
        }
    
    }


    public class ActionVoltar implements ActionListener{
        public void actionPerformed(ActionEvent event){
            dispose();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jProfessor;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel jTurma;
    private javax.swing.JButton jbBusca;
    private javax.swing.JButton jbVoltar;
    private javax.swing.JButton jbIncluir;
    private javax.swing.JLabel jlAlunoMatriculaEncontrado;
    private javax.swing.JLabel jlAlunoNomeEncontrado1;
    private javax.swing.JLabel jlMateria;
    private javax.swing.JLabel jlMedia;
    private javax.swing.JLabel jlProfessor;
    private javax.swing.JTextField jtAluno;
    private javax.swing.JTextField jtMatricula;
    private javax.swing.JTextField jtP1;
    private javax.swing.JTextField jtP2;
    private javax.swing.JTextField jtP3;
    private javax.swing.JTable jtProvas;
    // End of variables declaration//GEN-END:variables


}