/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interfaces;

import javax.swing.*;
import java.util.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author lipen
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();

    }


    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents

    @SuppressWarnings("unchecked")
    private void initComponents() {

        jdLogin = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmiProfessor = new javax.swing.JMenu();
        cadastrarP = new javax.swing.JMenuItem();
        incluirNota = new javax.swing.JMenuItem();
        incluirProvas = new javax.swing.JMenuItem();
        jmAluno = new javax.swing.JMenu();
        cadastrarA = new javax.swing.JMenuItem();
        consultarDadosA = new javax.swing.JMenuItem();
        


        ActionCadastrarP actionCadastrarP = new ActionCadastrarP();

        ActionCadastrarA actionCadastrarA = new ActionCadastrarA();

        ActionConsultaA actionConsultaA = new ActionConsultaA();

        ActionIncluirNota actionIncluirNota = new ActionIncluirNota();

        ActionIncluirProvas actionIncluirProvas = new ActionIncluirProvas();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Escola");
        getContentPane().setLayout(null);

        jLabel1.setText("Senha");
        jdLogin.add(jLabel1);
        jLabel1.setBounds(360, 200, 60, 16);

        jLabel2.setText("Login");
        jdLogin.add(jLabel2);
        jLabel2.setBounds(360, 130, 70, 16);
        jdLogin.add(jTextField2);
        jTextField2.setBounds(340, 150, 90, 22);
        jdLogin.add(jPasswordField1);
        jPasswordField1.setBounds(340, 220, 90, 22);

        getContentPane().add(jdLogin);
        jdLogin.setBounds(50, 25, 1080, 580);

        jmiProfessor.setText("Professor");
       

        cadastrarP.setText("Cadastrar");
        cadastrarP.addActionListener(actionCadastrarP);
        jmiProfessor.add(cadastrarP);

        incluirNota.setText("Incluir Nota");
        incluirNota.addActionListener(actionIncluirNota);
        jmiProfessor.add(incluirNota);

        incluirProvas.setText("Incluir Provas");
        incluirProvas.addActionListener(actionIncluirProvas);        
        jmiProfessor.add(incluirProvas);

        jMenuBar1.add(jmiProfessor);

        jmAluno.setText("Aluno");
        
        cadastrarA.setText("Cadastrar");
        cadastrarA.addActionListener(actionCadastrarA);
        jmAluno.add(cadastrarA);

        consultarDadosA.setText("Consulta Notas");
        consultarDadosA.addActionListener(actionConsultaA);
        
        jmAluno.add(consultarDadosA);

        

        jMenuBar1.add(jmAluno);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 1159, 672);
    }


   private class ActionCadastrarP implements ActionListener{
        public void actionPerformed(ActionEvent event){

        jifCadastroP obj = new jifCadastroP();
        jdLogin.add(obj);
        obj.setVisible(true);


        }
    }    

    private class ActionCadastrarA implements ActionListener{
        public void actionPerformed(ActionEvent event){
        jifCadastroA obj = new jifCadastroA();
        jdLogin.add(obj);
        obj.setVisible(true);

        }
    }

    private class ActionConsultaA implements ActionListener{
        public void actionPerformed(ActionEvent event){
            jifConsultaA obj = new jifConsultaA();
            jdLogin.add(obj);
            obj.setVisible(true);
        }
    }

    private class ActionIncluirNota implements ActionListener{
        public void actionPerformed(ActionEvent event){
            jifIncluirNota obj = new jifIncluirNota();
            jdLogin.add(obj);
            obj.setVisible(true);
        }
    }

    private class ActionIncluirProvas implements ActionListener{
        public void actionPerformed(ActionEvent event)
        {
            jifIncluirProvas obj = new jifIncluirProvas();
            jdLogin.add(obj);
            obj.setVisible(true);
        }
    }

    


   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

       
        
   
        java.awt.EventQueue.invokeLater(() -> {
            new Principal().setVisible(true);
        });



        
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadastrarA;
    private javax.swing.JMenuItem cadastrarP;
    private javax.swing.JMenuItem consultarDadosA;
    private javax.swing.JMenuItem incluirNota;
    
    private javax.swing.JMenuItem incluirProvas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JDesktopPane jdLogin;
    private javax.swing.JMenu jmAluno;
    private javax.swing.JMenu jmiProfessor;
    // End of variables declaration//GEN-END:variables
}
